spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
          filters:
            - StripPrefix=1
        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq
          filters:
            - StripPrefix=1
        ##前端项目请求都带有/api
        ##商品api
        - id: product_route
          uri: lb://glsc-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        ##用户api
        - id: member_route
          uri: lb://glsc-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        ##优惠api
        - id: coupon_route
          uri: lb://glsc-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        ##库存api
        - id: ware_route
          uri: lb://glsc-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        ##第三方服务api
        - id: third_party_route
          uri: lb://glsc-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}
        ##后端微服务renren-fast统一处理/api前缀
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
        ##商城主页
        - id: glsc_host_route
          uri: lb://glsc-product
          predicates:
            - Host=**.glsc.com, glsc.com, 192.168.189.130
