spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
          filters:
            - StripPrefix=1
        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq
          filters:
            - StripPrefix=1
        ##前端项目请求都带有/api
        ##商品api
        - id: product_route
          uri: lb://glsc-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        ##第三方服务api
        - id: product_route
          uri: lb://glsc-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}
        ##后端微服务renren-fast统一处理/api前缀
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
